# Generated by Django 5.1.4 on 2025-02-22 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='events',
        ),
    ]
