# Generated by Django 5.1.4 on 2025-02-20 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='user',
            field=models.OneToOneField(default='null', on_delete=django.db.models.deletion.CASCADE, related_name='Participant', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
