# Generated by Django 5.1.4 on 2025-02-22 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_participants'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Participant',
        ),
        migrations.AddField(
            model_name='event',
            name='thumb',
            field=models.ImageField(blank=True, default='events_thumbnail/default_thumb.jpg', null=True, upload_to='events_thumbnail'),
        ),
    ]
